apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Values.proxy.service.port }}-tcp
    port: {{ .Values.proxy.service.port }}
    protocol: TCP
    targetPort: {{ .Values.proxy.service.port }}
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP