apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Release.Name }}
spec:
  ingress:
  - ports:
    - port: {{ .Values.proxy.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
